package app.rutherford.auth.exception

class UserAlreadyExistException : RuntimeException()
